# Generated by Selenium IDE
import time
import json

import xlwt
import csv
import requests as req
from PIL import Image
from io import BytesIO


file = open("allbooks.csv")
csvreader = csv.reader(file)
header = next(csvreader)
print(header)
allbooks = []
for row in csvreader:
    allbooks.append(row[0])
print(allbooks)
file.close()

bookdata = []

# open the file for error logging
f = open('error_book_codes.csv', 'w')
# create the csv writer
writer = csv.writer(f)

workbook = xlwt.Workbook()
worksheet1 = workbook.add_sheet('Test')
worksheet1.write(0, 0, 'Title')
worksheet1.write(0, 1, 'Author')
worksheet1.write(0, 2, 'Description')
worksheet1.write(0, 3, 'image path')
i = 1
for book in allbooks:
    print("count : ", i)
    print("=======>>>>>> : ", book)

    # time.sleep(1)
    try:
        h = {'Authorization': '48596_393ce8a279fb43a8842bae6960df32a0'}
        resp = req.get("https://api2.isbndb.com/book/"+book, headers=h)
        # print(resp.json())

        # driver.find_element(By.LINK_TEXT, "978-6-8493-0196-6").click(
        # ),    driver.find_element(By.CSS_SELECTOR, ".title-description").click()
        print(type(resp.json()))
        print(resp.json())
        if "message" in resp.json():
            if resp.json()["message"] == "Forbidden":
                break

        print("-------------------\n\r")
        book_title = resp.json()["book"]["title_long"]
        book_author = resp.json()["book"]["authors"][0]
        if "synopsis" in resp.json()["book"]:
            book_description = resp.json()["book"]["synopsis"]
        else:
            book_description = ""
        book_imageURL = resp.json()["book"]["image"]

        # with open(book+'.jpg', 'wb') as file:
        #     response = requests.get(resp.json()['image'])
        #     img = Image.open(BytesIO(response.content))
        #     BookImage = img
        #     file.write(BookImage.screenshot_as_png)
        # Description = driver.find_element(
        #     By.CSS_SELECTOR, ".title-description")

        print("\n\r\n\r\n\r===============================================================\n\r\n\r\n\r")
        print("Title : ", book_title)
        print("\n\rAuthor : ", book_author)
        print("\n\rDescription : \n\r", book_description)
        print("\n\rBookImage.src : ", book_imageURL)
        print("\n\r\n\r\n\r-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n\r\n\r\n\r")
        # # worksheet1.insert_bitmap_data(fo.getvalue(), 0, 0)
        worksheet1.write(i, 0, book_title)
        worksheet1.write(i, 1, book_author)
        worksheet1.write(i, 2, book_description)
        worksheet1.write(i, 3, book_imageURL)
        i += 1

    except Exception as e:
        print(e)
        # write a row to the csv file
        writer.writerow(book)
        print("\n\r error in : ", book, "n\r\n\r")

    # time.sleep(960)
workbook.save('bookdata1.xls')

# close the file
f.close()
