# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from webdriver_manager.firefox import GeckoDriverManager
import xlwt
from selenium.webdriver.firefox.service import Service as FirefoxService
allbooks = ["9781501180996", "9780525557623", "9781663608444", "9780060590307", "9780060735449", "9781476716749", "9781101911945", "9781982137632",
            "9780525566106", "9781335284808", "9780778311140", "9780451457813", "9780857683168", "9780316013260", "9780062645234", "9781590171998", "9781400077915", ]
bookdata = []

# allbooks = []
# opts = webdriver.ChromeOptions()
# opts.headless = False
# assert opts.headless
# service = FirefoxService(executable_path=GeckoDriverManager().install())
# driver = webdriver.Firefox(service=service)

# options = webdriver.ChromeOptions()
# options.add_argument("start-maximized")

options = webdriver.ChromeOptions()
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option('useAutomationExtension', False)
options.add_argument("--disable-blink-features=AutomationControlled")
driver = webdriver.Chrome(
    './chromedriver_linux64/chromedriver', options=options)
# driver = webdriver.Chrome('./chromedriver_linux64/chromedriver')

vars = {}
workbook = xlwt.Workbook()
worksheet1 = workbook.add_sheet('Test')
worksheet1.write(0, 0, 'Title')
worksheet1.write(0, 1, 'Author')
worksheet1.write(0, 2, 'Description')
worksheet1.write(0, 3, 'image path')
i = 1
for book in allbooks:
    print("=======>>>>>> : ", book)
    driver.get("https://bookshop.org/")
    driver.set_window_size(1848, 1080)
    time.sleep(2)
    driver.set_window_size(1848, 1080)
    driver.find_element(By.NAME, "keywords").click()
    driver.find_element(By.NAME, "keywords").send_keys(book)
    driver.find_element(By.CSS_SELECTOR, ".is-secondary > img").click()
    driver.find_element(By.CSS_SELECTOR, ".product-image").click()
    time.sleep(2)
    # driver.find_element(By.LINK_TEXT, "978-6-8493-0196-6").click(
    # ),    driver.find_element(By.CSS_SELECTOR, ".title-description").click()
    Title = driver.find_element(By.CSS_SELECTOR, ".h1.leading-tight.mb-2")
    Author = driver.find_element(
        By.CSS_SELECTOR, ".text-secondary > span > span")
    with open(book+'.jpg', 'wb') as file:
        BookImage = driver.find_element(
            By.ID, "main\-image").find_element(By.CSS_SELECTOR, "div > a > img")
        file.write(BookImage.screenshot_as_png)
    Description = driver.find_element(By.CSS_SELECTOR, ".title-description")

    print("\n\r\n\r\n\r===============================================================\n\r\n\r\n\r")
    print("Title : ", Title.text)
    print("\n\rBookImage.src : ", BookImage.get_attribute("src"))
    print("\n\rAuthor : ", Author.text)
    print("\n\rDescription : \n\r", Description.text)
    print("\n\r\n\r\n\r-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n\r\n\r\n\r")
    # worksheet1.insert_bitmap_data(fo.getvalue(), 0, 0)
    worksheet1.write(i, 0, Title.text)
    worksheet1.write(i, 1, Author.text)
    worksheet1.write(i, 2, Description.text)
    worksheet1.write(i, 3, BookImage.get_attribute("src"))
    i += 1
    driver.get("https://bookshop.org/")
    # time.sleep(960)
    # driver.find_element(
    #     By.CSS_SELECTOR, "#main-image > .reletive > .block > .w-full").click()
# time.sleep(60)
workbook.save('bookdata.xls')

driver.quit()
