# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test3(self):
    self.driver.get("https://bookshop.org/")
    self.driver.set_window_size(1848, 1080)
    self.driver.find_element(By.NAME, "keywords").click()
    self.driver.find_element(By.NAME, "keywords").send_keys("9781501180996")
    self.driver.find_element(By.CSS_SELECTOR, ".is-secondary > img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-image").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#main-image .block > .w-full")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.execute_script("window.scrollTo(0,106)")
    self.driver.find_element(By.CSS_SELECTOR, ".title-description").click()
    self.driver.find_element(By.CSS_SELECTOR, ".measure").click()
    self.driver.find_element(By.CSS_SELECTOR, ".measure").click()
  
