# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.find_element(By.ID, "lightboxOverlay").click()
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win9984"])
    self.driver.find_element(By.CSS_SELECTOR, "img").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.CSS_SELECTOR, "img").click()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.ID, "main-image").click()
    self.driver.find_element(By.ID, "content").click()
    self.driver.find_element(By.ID, "content").click()
    self.driver.find_element(By.ID, "content").click()
    self.driver.find_element(By.ID, "content").click()
    self.driver.find_element(By.ID, "content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".branding > img").click()
    self.driver.get("https://bookshop.org/books/the-outsider-9781508252214/9781501180996")
    self.driver.set_window_size(1848, 1080)
    self.driver.find_element(By.CSS_SELECTOR, "#main-image .block > .w-full").click()
  
