# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    # Test name: test1
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://bookshop.org/")
    # 2 | setWindowSize | 1848x1080 | 
    self.driver.set_window_size(1848, 1080)
    # 3 | click | name=keywords | 
    self.driver.find_element(By.NAME, "keywords").click()
    # 4 | type | name=keywords | 9781501180996
    self.driver.find_element(By.NAME, "keywords").send_keys("9781501180996")
    # 5 | sendKeys | name=keywords | ${KEY_ENTER}
    self.driver.find_element(By.NAME, "keywords").send_keys(Keys.ENTER)
    # 6 | click | css=.product-image | 
    self.driver.find_element(By.CSS_SELECTOR, ".product-image").click()
    # 7 | click | css=.measure | 
    self.driver.find_element(By.CSS_SELECTOR, ".measure").click()
    # 8 | click | css=.text-secondary > span > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-secondary > span > span").click()
    # 9 | runScript | window.scrollTo(0,318) | 
    self.driver.execute_script("window.scrollTo(0,318)")
  
